[package]
name = "day25-22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common    = { path = "../common" }
log       = "0.4.17"
itertools = "0.10.5"
num       = "0.4.0"
